CREATE TABLE IF NOT EXISTS users (
  id BIGINT NOT NULL AUTO_INCREMENT,
  name VARCHAR(50) NOT NULL,
  surname VARCHAR(50) NOT NULL,
  uuid VARCHAR(50) NOT NULL,
  PRIMARY KEY (id));


CREATE TABLE IF NOT EXISTS auth_users (
  id BIGINT NOT NULL AUTO_INCREMENT,
  login VARCHAR(50) NOT NULL,
  password VARCHAR(255) NOT NULL,
  status VARCHAR(25) NOT NULL,
  created TIMESTAMP NOT NULL,
  updated TIMESTAMP NOT NULL,
  PRIMARY KEY (id));


CREATE TABLE IF NOT EXISTS roles (
  id BIGINT NOT NULL AUTO_INCREMENT,
  name VARCHAR(25) NOT NULL,
  PRIMARY KEY (id));


CREATE TABLE IF NOT EXISTS auth_user_roles (
  auth_user_id BIGINT NOT NULL,
  role_id BIGINT NOT NULL,
  CONSTRAINT fk_auth_user
     FOREIGN KEY (auth_user_id)
     REFERENCES auth_users (id)
     ON DELETE CASCADE
     ON UPDATE RESTRICT,
  CONSTRAINT fk_role
     FOREIGN KEY (role_id)
     REFERENCES roles (id)
     ON DELETE CASCADE
     ON UPDATE RESTRICT);